--- #YAML:1.0
name:               Bundle-W3C-Validator
version:            1.4
abstract:           Bundle of modules required by the W3C Markup Validator
author:
    - W3C QA-dev Team <public-qa-dev@w3.org>
license:            open_source
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    CGI:                  3.40
    CGI::Carp:            0
    Config:               0
    Config::General:      2.32
    Encode:               0
    Encode::Alias:        0
    Encode::HanExtra:     0
    Encode::JIS2K:        0
    File::Spec::Functions:  0
    HTML::Encoding:       0.52
    HTML::HeadParser:     3.60
    HTML::Parser:         3.24
    HTML::Template:       2.6
    HTML::Tidy:           0
    HTTP::Headers::Auth:  0
    HTTP::Headers::Util:  0
    HTTP::Message:        1.52
    HTTP::Negotiate:      0
    HTTP::Request:        0
    JSON:                 2
    LWP::UserAgent:       2.032
    Net::hostent:         0
    Net::IP:              0
    SGML::Parser::OpenSP:  0.991
    Socket:               0
    URI:                  1.53
    URI::Escape:          0
    URI::file:            0
    URI::Heuristic:       0
    XML::LibXML:          1.73
resources:
    bugtracker:   http://www.w3.org/Bugs/Public/
    homepage:     https://validator.w3.org/
    MailingList:  http://lists.w3.org/Archives/Public/www-validator/
    repository:   http://dvcs.w3.org/hg/markup-validator/
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
